### PR TITLE
Rename RPKI_Manifest because go-style.

### PR DESCRIPTION
**Pull request by morrowc**
Go style (https://golang.org/doc/effective_go.html#mixed-caps) says no to underscorery. (undersourcery?)

RPKI_Manifest should really be: RPKIManifest.

### CODE REVIEW

**Comment by morrowc** [comment]
sorry, enough fiddling with this... if this is ok, I'll have a gander through the rest as well.

**Comment by lspgn** [comment]
LGTM. Thank you @morrowc for doing this!
One thing though: I'm ok using GitHub Actions but the testing/build is done with Travis at the moment: I would like to avoid having both.

**Comment by morrowc** [comment]
Yup, the actions thing was mostly for me. I can pull that back in the morning.

**Comment by morrowc** [comment]
btw: removed the github-actions bits.

**Pull request merged**
